### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by hoangtrung99** [zhaqian12/ZQ-Keyboard#2]
Hi.
I am using Spark67 R3 keyboard. When I put my keyboard into DFU mode get this information from INFO_UF2.TXT  file
I don't get it in QMK Toolbox, I don't know how my keyboard can flash firmware. Can i build a firmware for my Spark67 R3 to use VIAL software?.
Please reply me if you have free time, thank you very much.
```
UF2 Bootloader v2.1.1-dirty
Model: ZhaQian STM32F103x
Board-ID: REV 1.0
```

**Comment by zhaqian12** [comment]
1.How to flash firmware: You just convert the firmware to uf2 format and then drag it into the disk.
2.How to build: In QMK, you only need to set the firmware format like this.
`FIRMWARE_FORMAT = uf2`
Then use the custom bootloader.
`BOOTLOADER = custom`
3.About spark 67r3, you can see here: https://github.com/zhaqian12/qmk_firmware/tree/zhaqian/keyboards/zhaqian/sp67

**Comment by hoangtrung99** [comment]
@zhaqian12 
OMG, that's amazing, that's all I needed, thank you so much. You are a wonderful person. :100: :100: :100:

**Comment by hoangtrung99** [comment]
@zhaqian12 
I have a question, so now what I need to do is
1. Edit and copy the SP67 folder to the vial-qmk folder.
2.Build vial-firmware
3. Convert the firmware to uf2 format and drag it to disk. (Can you give me a rough guide on what to use to convert, sorry I'm a web developer.)

Thank you very much. :pray:

**Comment by zhaqian12** [comment]
In QMK,you just need to add `FIRMWARE_FORMAT = uf2` in rules.mk.
You can check out the code I provided.

**Comment by hoangtrung99** [comment]
@zhaqian12 

Oh, so it's just that, that's great, thank you very much.

**Comment by hoangtrung99** [comment]
@zhaqian12 
Sorry, i can only build firmware today, but got this error, please help me 🙏 
![Screen Shot 2022-10-31 at 09 42 08](https://user-images.githubusercontent.com/29956745/198920022-150ea9b9-69e5-4ed5-9b7d-c7aa7fdb49d7.png)

**Comment by hoangtrung99** [comment]
@zhaqian12
```
MCU_LDSCRIPT = STM32F103x8
```
I fixed like this and build the firmware, but I can't pull the firmware to disk.

**Comment by hoangtrung99** [comment]
@zhaqian12 
I don't understand, now even I don't see the keyboard recognized, when I connect to the USB port, the ZhaQian DFU volumes are not displayed.

**Comment by hoangtrung99** [comment]
> @zhaqian12 I don't understand, now even I don't see the keyboard recognized, when I connect to the USB port, the ZhaQian DFU volumes are not displayed.

Before that i tried to format the disk, but the situation is the same as in the video, don't know if this affects and what i need to do :(

**Comment by hoangtrung99** [comment]
@zhaqian12 
Please help me, i don't know what to do next to save my keyboard :(

**Comment by zhaqian12** [comment]
1.If you want to go to DFU mode, please press the reset button twice on the PCB to go to the bootloader.
2.About the linking file xxx.ld, see here: https://github.com/zhaqian12/qmk_firmware/blob/zhaqian/platforms/chibios/boards/STM32_F103_STM32DUINO/ld/STM32F103x8_uf2.ld

**Comment by hoangtrung99** [comment]
@zhaqian12 

> 1.If you want to go to DFU mode, please press the reset button twice on the PCB to go to the bootloader.

I can't find the reset button on the PCB board :(
Does Spark67's PCB have no hard reset button?

> 2.About the linking file xxx.ld, see here: https://github.com/zhaqian12/qmk_firmware/blob/zhaqian/platforms/chibios/boards/STM32_F103_STM32DUINO/ld/STM32F103x8_uf2.ld

Thank you so much, I was looking for it but couldn't find it.

**Comment by zhaqian12** [comment]
It's on the bottom of the PCB, close to the space. Maybe you need tweezers to trigger it.

**Comment by hoangtrung99** [comment]
@zhaqian12 
Please help me mark that place
![image](https://user-images.githubusercontent.com/29956745/199415994-da45b156-ae37-49e4-8e52-f8d5d54778b8.jpeg)

**Comment by hoangtrung99** [comment]
@zhaqian12 
I checked both the top and bottom side, there is no reset button.

**Comment by hoangtrung99** [comment]
@zhaqian12 
Yeahhhh! I fixed it, thank you very much 🙏 
![Screen Shot 2022-11-02 at 15 58 56](https://user-images.githubusercontent.com/29956745/199453410-36a27bb6-ebb1-460c-a77b-e2a0233c6694.png)

**Comment by hoangtrung99** [comment]
@zhaqian12 
Hmmm, I found out I have a problem.
I fixed it by connecting ST-LINK to the circuit at  [GND SWD CLK 3v3] ports, then I used `STM32 Untility` software to flash the `.bin (from .build folder)` file I built according to your code above, it basically works good, but i can't get into bootloader using bootmagic, i tried everything but no success. Do you know the reason why? what should i try to do other than reset by physical key.
